// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let max = 4000000;

let prevNumber = 1;
let nextNumber = 2;
let numberArray = [];
let evenSum = 0;

while(nextNumber < max) {
    console.log(prevNumber, nextNumber);

    let oldPrevNumber = prevNumber;
    let oldNextNumber = nextNumber;

    if (nextNumber % 2 === 0 && nextNumber < max) {
        numberArray.push(nextNumber);
        evenSum += nextNumber;
    }
    
    prevNumber = oldNextNumber; // 2
    nextNumber = oldPrevNumber + nextNumber; // 1 + 2 = 3
}

console.log(numberArray);
console.log(evenSum);